language: node_js
node_js:
  - "6"
addons:
  sauce_connect: true
  jwt:
    secure: "oP5toakDdqhCnUmDw3Uj6mAJLixkbKP3WkER7WrpQXB1ruyld76siggEL3wkNG0PTZmBlR9zF2cJyX2ygMIjhwrmZX9gLj2sXgK2qxfdzBEUiJWX9nPwdubBx1AtWqtcDaftbEWq/+k5GOUAO0Q8eT3/T1zrVTGhF61+dIqe0p8xwnPehymA7VQmany5H7ekqmt+P0klzXmN0grLLGpBaqZj7jWww890moYGkOcfcNGXrbeBl1hNiNADgw9reTtZfGclmV7ngAXMjiEGk2jbbT8Ee26to7nF7WHb7hN49JgnutATtVESB8z2qSrVf87S/e5XytM+vyTE2l3E5MVPrtl2xg7ZkpWvAjLkwQ7R8lo4VwjTYV57GADoE3psa/LK7zE9zMcfe+1qbYpN4dnul2KAt1DnZ8rmqbRsQMP4aZld+hevmFsE3DC39KoURwU8yVKDbklqJgIP3GL9Aux3IxmzmO6dRSoA4ba9dkH1ACPwG5qRfgO8+uHpnt4neli5WwBu6wv/QjquLw0VetX8aR2s0Y5UQnEj/YGIDkhjHUKAFyLCqqnNUvDYzysd5uR2DS8uPA/vYqsoq/dWIUzvgP3BJ8RNlVzdczr5H9wjuAcPt01hTNp9T0CzN2Wl84Wt9LW+QWxEFrouttp9kUcQ5rCs/GHtYm18cdZQmoPWj2A="
after_script:
  - codeclimate-test-reporter < dist/coverage/lcov.info
before_deploy:
  - node tools/setupDeploy
deploy:
  provider: script
  script: npm publish dist/src 
  skip_cleanup: true
  on:
    tags: true