language: node_js
node_js:
  - "8"
addons:
  sauce_connect: true
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
before_deploy:
  - node ./tools/setupDeploy
deploy:
  provider: script
  script: ./tools/deployment.sh 
  skip_cleanup: true
  on:
    tags: true