language: node_js
node_js:
  - "6"
addons:
  sauce_connect: true
  jwt:
    secure: "byf3eF2VgyUhqvrhHqw4CACMhkBeK4JambySXDwR2Or1dbDVFKgpeJ2cgmXKXAUqtDq5HIV2TCsa0w8UBLI/KvU7hUw+yS1pF+ZjoebLX7NiOG41mRxfpsgSfDtfobLGAO5+/ZPubYsmNa5QuKAKMumpV6nKoMjc5Q8zXvuI3CV9S0fbcfrRwrgs9v4gKwRcR8ioA/x1GcQ560IMonHRSn+PjYS0RnhqkEsCY2Scvq49nMeMcpMJ6wAIORDnZ5QQxRTIRYb6IlaxJkjilvd9JSn6SvJNbfvk7D0G/cCxCINpNGiw1S6K46YKaxvQZUlc7E/nE8aJRgpNxPnwI6h6seZ06il+kRBBp/CMnJ7H/YIdtlCT9i0OkDTp3nxr27sjBF38z/vhqS8VLHQSsFd9/edd3cuaYqOhRBn3WNappf9LqguaDpmaXQ0YWNQrQdI1wkOZQO9vi/69XgduQn5BsU6TbbLyRl9UNc+Je+cuzUMAQNuSpFoMYBLrxnPPn0aMNerDb/Ux+tQ65nET4z2sXrLLuXAt7IAMhsrUflQPXWDl+4+h8J+v6hvvQMSnsxFpXqYTgaM5W5Ga2KCoBf7GRba9MWgieV0lEKsgVQzp3f0SRHpZ7DSSS3jEVnjrMTogz4jdBz57/KNOo4Ig4pClB8TB34jx635iJmoEisGfoHo="
after_script:
  - codeclimate-test-reporter < dist/coverage/lcov.info
before_deploy:
  - node tools/setupDeploy
deploy:
  provider: script
  script: npm publish dist/src 
  skip_cleanup: true
  on:
    tags: true